---
- name: Ansible playbook for installing and configuring k3s
  hosts: all
  remote_user: ubuntu

  tasks:
    - name: Install k3s
      become: true
      shell: curl -sfL https://get.k3s.io | sh -

    - name: Copy kubeconfig to the local machine
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: ~/.kube/config
        flat: yes
      become: true

    - name: Edit kubeconfig to point to the correct server
      local_action:
        module: lineinfile
        path: ~/.kube/config
        regexp: '    server: https://127.0.0.1:6443'
        line: '    server: https://{{ lookup("env", "K3S_IP") }}:6443'
        backrefs: yes